#Cluster Details
NUM_MANAGERS=1
NUM_WORKERS=2
PREFIX=vijay

WORKER_ZONE=d
WORKER_REGION=us-east-1
WORKER_VPCID=vpc-e46cb483
export WORKER_ACCESS_KEY=AKIAJ6DGCFCI3TE6SPKA
export WORKER_SECRET_KEY=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

MANAGER_ZONE=d
MANAGER_REGION=us-east-1
MANAGER_VPCID=vpc-e46cb483
export MANAGER_ACCESS_KEY=AKIAJ6DGCFCI3TE6SPKA
export MANAGER_SECRET_KEY=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
